### ISSUE TITLE
Game not found

### ISSUE THREAD

**Issue by Hakuchuu** [randomidiot13/queueclient-web#2]
Hi, sometimes I can't find the games to fetch, prompting that it's an invalid game. For example, Getting Over It With Bennett Foddy. I have tried getting_over_it and getting_over_it_with_bennett_foddy, but both are invalid.

**Comment by tildejustin** [comment]
https://www.speedrun.com/goiwbf < the id is `goiwbf`

**Comment by Hakuchuu** [comment]
I get it now, thanks for the reply
